openapi: 3.0.1
info:
  title: p4pa-migration
  description: Api and Models
  version: 0.0.1
servers:
  - url: http://localhost:8080/migration
paths:
  /{migrationFileType}:
    post:
      tags:
        - migration-file
      summary: uploadMigrationFlowFile
      description: Service to store an migration file
      operationId: uploadMigrationFile
      parameters:
        - name: migrationFileType
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MigrationFileTypeEnum'
        - name: organizationId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          'multipart/form-data':
            schema:
              required:
                - migrationFile
              type: object
              properties:
                migrationFile:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadMigrationFileResponseDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /workflows/{workflowId}/status:
    get:
      tags:
        - Workflow
      operationId: getWorkflowStatus
      summary: Get Workflow Status
      description: Retrieve the current status of a Temporal workflow by its ID.
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Workflow status retrieved successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatusDTO'
        '404':
          description: "Workflow not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /upload/debt-positions-type-org-operators:
    post:
      tags:
        - upload
      summary: uploadDebtPositionTypeOrgOperatorsFile
      description: Service to store and process an operator/debtPositionTypeOrg migration file
      operationId: uploadDebtPositionTypeOrgOperatorsFile
      parameters:
        - name: organizationId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          'multipart/form-data':
            schema:
              required:
                - debtPositionTypeOrgOperatorsFile
              type: object
              properties:
                operatorFile:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadMigrationFileResponseDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    MigrationFileTypeEnum:
      type: string
      enum:
        - ORGANIZATIONS
        - DEBT_POSITIONS_TYPE_ORG_OPERATORS
    UploadMigrationFileResponseDTO:
      type: object
      required:
        - uploadId
        - workflowId
        - runId
      properties:
        uploadId:
          type: integer
          format: int64
        workflowId:
          type: string
        runId:
          type: string
    WorkflowCreatedDTO:
      type: object
      required:
        - workflowId
        - runId
      properties:
        workflowId:
          type: string
        runId:
          type: string
    WorkflowStatusDTO:
      type: object
      required:
        - workflowId
        - workflowType
        - status
        - runId
        - taskQueue
      properties:
        workflowId:
          type: string
        workflowType:
          type: string
        status:
          type: string
        runId:
          type: string
        taskQueue:
          type: string
        startDateTime:
          type: string
          format: date-time
        executionDateTime:
          type: string
          format: date-time
        endDateTime:
          type: string
          format: date-time
        duration:
          type: string
          format: duration
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - NOT_FOUND
            - BAD_REQUEST
            - GENERIC_ERROR
            - FILE_UPLOAD_ERROR
            - INVALID_FILE
        message:
          type: string
